version: '3'
services:
  covalence:
    build:
      context: ./tools/covalence
      args:
        covalence_version: $COVALENCE_VERSION
        gemfury_token: $GEMFURY_TOKEN
    image: "${COVALENCE_REGISTRY:-unifio/covalence}:${COVALENCE_VERSION}"
  packer:
    build:
      context: ./tools/packer
      args:
        packer_version: $PACKER_VERSION
    image: "${PACKER_REGISTRY:-unifio/packer}:${PACKER_VERSION}"
  terraform:
    build:
      context: ./tools/terraform
      args:
        terraform_version: $TERRAFORM_VERSION
    image: "${TERRAFORM_REGISTRY:-unifio/terraform}:${TERRAFORM_VERSION}"
